//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ConfigId { get; set; }
        public string Keyword { get; set; }
        public string Domain { get; set; }
        public string HotLine { get; set; }
        public string Social { get; set; }
        public string EmailSent { get; set; }
        public string MailPass { get; set; }
        public string PageTitle { get; set; }
        public string GooleMap { get; set; }
        public Nullable<long> ShowPageId { get; set; }
        public string Youtube { get; set; }
        public string Sky { get; set; }
        public string Yahoo { get; set; }
        public string Mail { get; set; }
        public string Slogan { get; set; }
        public string Address { get; set; }
        public string Hotline1 { get; set; }
        public string Hotline2 { get; set; }
        public string Yahoo1 { get; set; }
        public string Yahoo2 { get; set; }
        public string Sky1 { get; set; }
        public string Sky2 { get; set; }
        public string MailRetrive { get; set; }
        public string Facebook { get; set; }
        public string Google { get; set; }
        public string Twiter { get; set; }
        public string Metadata { get; set; }
        public string Description { get; set; }
        public string CCmail3 { get; set; }
        public string CCmail4 { get; set; }
    }
}
