//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageList
    {
        public long ImageListId { get; set; }
        public string Image { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Title { get; set; }
        public Nullable<long> SoLuong { get; set; }
    }
}
