//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADV
    {
        public long AdvId { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public Nullable<int> Type { get; set; }
        public string Title { get; set; }
        public string Des { get; set; }
    }
}
