//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countview
    {
        public long CountViewId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> Counter { get; set; }
    }
}
