//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Phone { get; set; }
        public Nullable<int> AreaId { get; set; }
        public int Role { get; set; }
        public string Name { get; set; }
        public bool gender { get; set; }
    }
}
